### ISSUE TITLE
betapart R package

### ISSUE THREAD

**Issue by jvcasillas** [jvcasillas/many_analyses#13]
This will be extremely useful (I believe) for working through the functions in this package: 

https://besjournals.onlinelibrary.wiley.com/doi/10.1111/j.2041-210X.2012.00224.x

**Comment by troettge** [comment]
I pushed my first betapart attempt. A bunch of ?s because I am not entirely sure (a) how it does it (b) which comparison we are supposed to use and (c) why there are NaNs. Maybe a point of departure for you.

**Comment by troettge** [comment]
[script](https://github.com/jvcasillas/many_analyses/commit/b265364effd39a8d8f6c3d31e04faae34fea1570) that Hannah send me on their use of betapart. Its pretty meager from what I can see

**Comment by jvcasillas** [comment]
Awesome. I’ll jump on this this morning so we have more to discuss tomorrow.

**Comment by jvcasillas** [comment]
Ok. Based on the script it looks like the key part is this: 

```
sorensenmatrix<-as.matrix(beta.pair(SilberVariables, index.family="sorensen")$beta.sor) #creates the sorensen dissimilarity matrix
teamsimilarity<-colMeans(sorensenmatrix,na.rm=T) #takes the average dissimilarity for each column
```

Which between the two of us I think we already did (in the shennanigans parts). I was curious about what the values in the matrix had to be, but I see from their code it was the ES with an interval. So we can just use the estimates from the MA and do the same thing (if I understood correctly). I will add this in tonight.

**Comment by troettge** [comment]
Yeah, that’s exactly what we did already. But I haven’t fully understood why we get NaNs in some cells. You?

Timo

**Comment by troettge** [comment]
Ah I know saw you fixed it already. Nice! Looks really promising. 

T

**Comment by troettge** [comment]
You are right that the column need to be 1 vs. 0 (I think). I added dummy columns to the simulated df, so that we can streamline the analysis

**Comment by troettge** [comment]
added a plot for the distances according to random and fixed effect parameters. Unfortunately this does not show for example conservativeness. But if we plot simply the number of parameters for fixed and random on x and y for each team, one dimension will be conservativeness (more random effect parameter, more conservative). We can chat about these things tomorrow.

**Comment by jvcasillas** [comment]
Very cool. This is promising. I added another plot with the posterior medians for the effect size (from the MA) and plotted it as a function of the sorenson values for fixed and random effects.
