### ISSUE TITLE
Need input

### ISSUE THREAD

**Issue by stefanocoretta** [jvcasillas/many_analyses#19]
@jvcasillas @troettge I need your input on these items (we can discuss on Wed).

- *1.2 Crowdsourcing alternative analyses*
  - "Sum-up of Neuroscience Cognitive modeling Clinical Predictive models"
  - I am not sure what I should add here.
- *2.4.1 Descriptive statistics*
  - "We anticipate that the majority of statistical analyses will be expressible as a (generalized) linear regression model." ADD FORMULA
  - Is this just the general glm formula?
  - <img src="https://render.githubusercontent.com/render/math?math=E(Y|X) = \mu = g^{-1}(X\beta)">
- *2.4.2 Meta-analytical estimation*
   - Which predictors are we gonna include in the meta-analytical model?
- Is a CC-BY license for the data ok?

(linking the meeting minutes: #9)

**Comment by troettge** [comment]
Feedback: 
- 1.2: There are a bunch of papers that did many analyst projects, we need to summarize (see the list in our read me) and refer to.
- 2.4.1: i wonder whether we need any formula. I dont see any gain. Something to discuss
- 2.4.2: I think we decided to have a slim model with few predictors and then explore generously. Does that make sense? Something to discuss later.
- license: Data tables are anonymised, the raw data (sound files) need to be more restricted, correct?
