### ISSUE TITLE
Decide on a dataset

### ISSUE THREAD

**Issue by jvcasillas** [jvcasillas/many_analyses#2]
Current best option is Timo's German production data ([OFS repo](https://osf.io/3bmcp/)). 

Include in comments other possible datasets.

**Comment by troettge** [comment]
The whole thing is now up on our [own repo](https://osf.io/3bmcp/). I just invited you. I also pushed a detailed description of the study (--> docs) which is quite complicated when you read all the details. I think there are a couple of things to do here. Maybe you guys read the description carefully and go through the materials (maybe even run the experiment to get an idea what the fuck is going on). After that (if you still think its the right data set),  we need to (a) write the detailed method as clearly as possible (so edit it) and (b) write a less-detailed version that is even clearer. My thinking is, there are a lot of details that are not relevant for the analysis. If we can give them a crisp description of what the experiment does, I think most people would be fine with that. For those who want to dig deeper, we offer more details. I also think, maybe we need to allow for discussion of the method somewhere. What do you think?
