### ISSUE TITLE
RR does not compile after including ForkingPaths.png

### ISSUE THREAD

**Issue by stefanocoretta** [jvcasillas/many_analyses#28]
I am trying to fix the compilation issue introduced by the including the image `ForkingPaths.png`.

There were a few typos in the code, but now that those are fixed it still doesn't compile and the culprit is the papaja format. Do we need to use this format? Or can we just switch to a cleaner/simpler format? If we can, I am happy to change this (it's a quick thing), so we have better control over the settings and output.

(What was the journal we were thinking of submitting too again? Maybe they have a latex template and we can just use that as the tex template for knitr).

**Comment by jvcasillas** [comment]
This is a pretty simple fix. Papaja works best using bookdown style image insertions/captions. I'll fix it on my branch and submit a pull request.

**Comment by jvcasillas** [comment]
Just saw the fix fig branch. I'll fix it there.

**Comment by jvcasillas** [comment]
Fixed via https://github.com/jvcasillas/many_analyses/commit/aae9460b23726fc36299adddc5ac88cfd731dcab

Also, I set `floatsintext` to "yes" so that we can see how it looks in terms of dimensions.

**Comment by stefanocoretta** [comment]
Thanks for the fix! Yeah I think it would be better to just use either the template of the journal we want to submit to, or something we can customise off the default pandoc template. I think papaja is overkill. But let's discuss in the next meeting as you said. ☺️
