### ISSUE TITLE
Minutes - 2021/01/27

### ISSUE THREAD

**Issue by stefanocoretta** [jvcasillas/many_analyses#32]
### Action items

- [x] Write summary of prior meta studies (@troettge #31).
- [x] Check missing references in RR (@troettge).
- [x] Check https://journals.sagepub.com/home/amp for tex template (@jvcasillas).
  - [Guidelines](https://www.psychologicalscience.org/publications/ampps/ampps-submission-guidelines#STR>).
    - [Description](https://www.psychologicalscience.org/publications/ampps/ampps-submission-guidelines#RR)
    - Note: Can't find LaTeX template (JVC)
- [ ] Landing page, copy text to gdoc (@troettge ).
- Analysts journey (**all**).
  - [ ] Think about how to divide in steps (conceptually and visually).
  - [ ] Think about possible icons.
- [x] Continue RR draft (@stefanocoretta).
  - Edited the factor analysis section (still WIP).
- [x] Continue OSF prepping.
  - Prepared TextGrids.

### Discuss

- Timo will work on the landing page.
- [x] Structure of Reviewers questionnaire.
    - [x] @jvcasillas will do it. (ecoRR reviewer https://osf.io/4t36u/) (initial draft is in googledrive: many_analyses_peer_review_survey)
- [x] Check transcription of objects and colours.

**Comment by jvcasillas** [comment]
Regarding AMP [formatting](https://www.psychologicalscience.org/publications/ampps/ampps-submission-guidelines#REPL): 

>Manuscript Structure
>
>Submissions should follow the guidelines of the Publication Manual of the American Psychological Association (6th ed.) for references, abbreviations, and symbols. AMPPS encourages authors to embed figures in the manuscript near where they are referenced rather than to put all figures at the end. Similarly, tables should be embedded in the text unless they occupy more than one manuscript page; larger tables can be included at the end of the manuscript. After acceptance, authors will need to provide a high-quality version of each figure for production purposes.
>
>For the review process, AMPPS permits submission of an already-formatted article (generated using LaTeX, R Markdown, or other methods) in addition to the pdf or Word version that must be submitted as the primary manuscript file. Authors who wish to submit an already-formatted article in addition to the primary manuscript can submit both the formatted (“knit”) document and the file used to generate it as supplementary files. Such formatted documents (e.g., R Notebooks) allow for a completely reproducible process that incorporates both the manuscript text and analyses within a single file.
>
>Authors should provide access to working versions of any interactive demonstrations or tools (e.g., Shiny Apps, Tutorial videos). If the authors lack a way to host such content that would permit anonymous review, they should contact the editorial team before submission.

**Comment by stefanocoretta** [comment]
I forgot to make a pull request and I merged to the master branch directly, so I am pinging you here as a heads up to pull before making changes/pushing. @jvcasillas @troettge
