### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by troettge** [jvcasillas/many_analyses#33]
[logo proposal](https://github.com/jvcasillas/many_analyses/blob/master/figs/Logo_proposal.png). dunno... see here.

**Comment by jvcasillas** [comment]
I like the hat tip to Borges. I think it's great but I'd consider different color palettes.

**Comment by troettge** [comment]
those were just the three colors of the three bananas, lol. I’ll sit down and draw a little tonight ;)

T

**Comment by stefanocoretta** [comment]
Nice! What if you overlay the waveforms just on the word "SPEECH"? Maybe with a semitransparent layer, or using a mask. I'd also use a more appealing typeface. :)

**Comment by troettge** [comment]
[cleaner version](https://github.com/jvcasillas/many_analyses/blob/master/figs/Logo_proposal2.png), speech and forking paths visually there. What say you?

**Comment by jvcasillas** [comment]
These are great! I like them a lot. I like the hex workflow too. Good job.

**Comment by stefanocoretta** [comment]
I really like the latest version!!!

Could we maybe use a rounded sans-serif typeface? I don't mind [Varela Round](https://fonts.google.com/specimen/Varela+Round?preview.text=MANY%20SPEECH%20ANALYSES&preview.text_type=custom).

Or maybe a squared typeface that has a bigger width to height ratio?

What do yous think?

**Comment by troettge** [comment]
Hi,

How about I put up three version with different fonts and then we simply vote? Sounds good?

Timo

**Comment by troettge** [comment]
my ranking: 1 - Varela, 2 - Bebas

**Comment by stefanocoretta** [comment]
1. Varela (maybe bolder).
2. Toppan.

I like that these make the logo more 2:1 than 16:9.

**Comment by stefanocoretta** [comment]
You could play around with a squared/circle version too, for the socials. 😺

**Comment by jvcasillas** [comment]
Uggh Im horrible with fonts. I like all three. I would pick 1 - Bebas and 2 - Toppan (since you are making me).

**Comment by troettge** [comment]
Two Varella on Rank1. Varella it is. Boom. case closed :D

**Comment by stefanocoretta** [comment]
I would just use a bolder weight, although I just see that it does not have it but I can make it!
