### ISSUE TITLE
Minutes 2021-02-10

### ISSUE THREAD

**Issue by stefanocoretta** [jvcasillas/many_analyses#37]
### Action items

- [x] Continue working on surveys (@jvcasillas) (https://github.com/jvcasillas/many_analyses/issues/1#issuecomment-771687908)
- [x] Include information about German phonetics/phonology, consider linking to IPA chart in German
- [x] For logo, possibly make forking paths same width as word, consider font boldness, make plural
- [x] Look at landing page again, focus on text (everybody)

### Discuss

- Meta-analytical model.
  - Prior for the group-level standard deviation: HalfCauchy(0, 1) might be too wide.
- Considering making a `many_analyses.github.io` website.

**Comment by stefanocoretta** [comment]
Just a heads up that I am working on the simulations .Rmd, but the `r/` folder in `scripts/` was confusing brms so I made a `simulation/` folder in `scripts/`.

**Comment by jvcasillas** [comment]
Topics:

- discussed surveys (pretty much done, just minor editing)
- discussed German phonetics, @stefanocoretta will get this in the next few weeks
- discussed landing page, will remove "why" section and graphic (avoid giving too much info regarding researchers degrees of freedom)
- video has been updated (new mic)
- discussed stats:
    - half cauchy too wide (0.1), tried 0.01, seems more reasonable
    - data are ready, models fit (simulations.Rmd)
    - weird path error from here/brms/knitr interaction (solution: move `simulations.Rmd` outside of /scripts/r)
- Considered possibility of including knitted html files as part of landing page or separate website (github organization). Decided to create org and recreate landing page.

Todo: 

- continue with RR updates
- Create org, website (@jvcasillas)
