### ISSUE TITLE
Decide on possible venue

### ISSUE THREAD

**Issue by troettge** [jvcasillas/many_analyses#4]
- [x] make list of possible (RR compatible) and desirable venues
- [x] decide on venue to submit

**Comment by jvcasillas** [comment]
I will start throwing names out (even though I know we aren't necessarily interested in all of them)

- [Language learning](https://onlinelibrary.wiley.com/pb-assets/assets/14679922/LL_submission_requirements_RR_9_23-1569243804833.pdf)
- [Language and speech](https://www.sagepub.com/sites/default/files/registeredreportsguidelines_author.pdf)

**Comment by troettge** [comment]
List of all journals offering RRs:
https://www.cos.io/our-services/registered-reports

Some fitting venues to consider (plus links to guidelines). Ranked according to my perceived prestigious/journal reanking. My favorite remains "Advances in Methods and Practices in Psychological Science".

Nature Communications
https://www.nature.com/ncomms/submit/registered-reports

Nature Human Behaviour
https://www.nature.com/uploads/ckeditor/attachments/4825/RegisteredReportsGuidelines_NatureHumanBehaviour.pdf

Psychological Science 
https://www.psychologicalscience.org/publications/psychological_science/ps-submissions

Advances in Methods and Practices in Psychological Science https://www.psychologicalscience.org/publications/ampps/registered-report-guidelines

Experimental Psychology
https://us.hogrefe.com/fileadmin/user_upload/global/journals/Hogrefe_Publishing/Experimental_Psychology/Zea_INstructions_extended_final.pdf

PLOS One 
https://journals.plos.org/plosone/s/other-article-types

Collabra
https://docs.google.com/document/d/1eeXPEC_oc4OYlywC9pRt6seL2xazlT58jAtRsCuEdCI/edit
