### ISSUE TITLE
Storing dataset

### ISSUE THREAD

**Issue by troettge** [jvcasillas/many_analyses#6]
**Qs regarding dataset:**

All materials are right now on a privat OSF. Relevant files are
- the sound files (duh). Pretty big file folder (30files à 100+MB)
- relevant textgrids that we generated according to our prereg (see Q below)
- experimental files for two experiments: 1. A norming study to norm the typicality of modifier plus noun (e.g. blue banana) and 2. the production experiment. For 1., there is a github repository from a student of Michael who programmed that one.
For 2. we have images and trial lists in the OSF repo and I'm sure Simon has the code for the browser-based experiment somewhere. 

I think we should make all of this available to the analyst. It would be potentially helpful to make a screen recording of both the norming study and the actual experiment so that analyses teams can watch them and get a feel for the experiment.

**Okay my Qs**:
- How should we go about storing the dataset. OSF strikes me eventually as the better option.
- How should we go about the dataset per se. Maybe we should offer the analyses teams a text grid that at least labels relevant utterances and their experimental condition? What do you think?

**Comment by stefanocoretta** [comment]
I think OSF is a good option for storing the dataset. It does not have a storage limit per project (only 5GB limit per file, so no probs), which is a good.

Sharing a TextGrid with annotation/segmentation would be good. That is what usually takes a great portion of the overall time, and if we provide analysts with that, they might be more willing to do the rest of the work. Also, having the same segmentation makes comparison across teams "easier"?

**Comment by troettge** [comment]
I agree. Just to be clear, I envision providing text grids that only provide intervals for individual sentences. Analyst obviously need to segment (or at least I expect them to), these larger chunks into reasonable domains (for whatever they want to measure). Agreed, that this makes it a little bit less effortful for them.

**Comment by jvcasillas** [comment]
I agree that OSF should be the main way teams interact with everything project related. Github can be for material preparation for us.

**Comment by troettge** [comment]
So practically for now, how about I simply invite you to the OSF repo. To get a better idea about what happened in the experiment your could read our prereg and maybe  that helps us deciding whether this dataset is the one we want to use.

**Comment by troettge** [comment]
Done!
