### ISSUE TITLE
Minutes - 2021/01/13 and previous ones

### ISSUE THREAD

**Issue by stefanocoretta** [jvcasillas/many_analyses#9]
- Timo will send us the presentation file of the video and we can have a look at the script to see if/what we can simplify a few parts.
- Read through [docs/ExperimentalDetails](https://github.com/jvcasillas/many_analyses/tree/master/docs/ExperimentalDetails) to see if we can make it simpler and check experimental procedure against what is in the presentation video.
  - Maybe write a shorter Experimental Details doc? and link to extra info on OFS or the like.
- Research Question: move focus from "referring expression" (i.e. *the green banana*) to "utterance"? We don't want to bias the analysts to focus on the noun only.
- Check Joseph's google forms and docs (links here #1).

**Comment by troettge** [comment]
The .keynote presentation is up. 

Here are some versions of the research question I can think of:

- Do speakers acoustically modify utterances to signal atypical word combinations?
- Does the acoustic profile of an utterance reflect the typicality of referring expressions?
- Does the acoustic profile of an utterance reflect atypical adjective-noun combinations?

"acoustically" could be exchanged with "prosodically"

Some phrase we can play with. Maybe qualified by sth like: ...e.g. does the prosodic profile of "click on the yellow banana" differ from "click on the blue banana"?

**Comment by jvcasillas** [comment]
I prefer this version (for now): 

Do speakers acoustically modify utterances to signal atypical word combinations?

**Comment by jvcasillas** [comment]
10/30/2020

- draft method section
- iron out details of analysis
- talk about effect sizes, gamms
  - https://osf.io/9kj7h/ (talks about es calculation in hierarchical models)

**Comment by jvcasillas** [comment]
11/11/2020

- RE effect sizes (delta_t)
    - https://www.reddit.com/r/statistics/comments/fouwp9/q_effect_size_calculation_for_brms_delta_t/
    - https://www.barelysignificant.com/phd_thesis/appendix-brms.html#inference-and-conclusions
    - https://www.researchgate.net/publication/250185702_Effect_Sizes_in_Cluster-Randomized_Designs

**Comment by jvcasillas** [comment]
11/18/2020

- simplify reviewer evaluation (don't include "reject", etc. and numeric... just numeric)
- [ ] justify sample size
    - reread ecology rr
    - "This minimum sample size is invariant regardless of τ2. This is because the same t-statistic value will be obtained by the same sample size regardless of variance (τ2)."
- [ ] write method "statistical analysis" for meta-analysis
- [ ] write method "statistical analysis" for sorenson analysis
- [ ] make plots pretty

**Comment by jvcasillas** [comment]
11/24

- [ ] MA
    - [ ] add slopes to team and reviewer for reviewer rating
    - [ ] center/standardize predictors

**Comment by jvcasillas** [comment]
02-02

(From last week)

- [ ] Video
    - [ ] "advertisement" type text
    - [ ] general feedback
- [ ] Codebook
    - [ ] add description (README files)
- [ ] RR
    - [ ] clean up
    - [x] combine Sorensen sections
    - [ ] connection between acoustic analysis and analytic strategy

**Comment by jvcasillas** [comment]
12/09

- make lists of interesting/useful things for exploratory analyses
- next week we will discuss what we can/should do, finalize analytical plan

**Comment by jvcasillas** [comment]
12/16

For RR

- random forest explanation for RR (rank predictors, deal with colinearity)
- use results of random forest (ranking) for logistic regression
- put "Stefano" touch on prose
- basic fill in the gaps
- resolve possible conflicts

**Comment by stefanocoretta** [comment]
2020/12/23

* Summary of recent changes.

**Comment by stefanocoretta** [comment]
## 2021/01/06

### Pre-meeting notes

@troettge @jvcasillas 

Changes I have made:

- Edits to RR (including section Step 4, sample size justification, exploration variable list, paragraph on funnel plots).
- Added package osfr to manage the OSF repo (see [here](https://github.com/jvcasillas/many_analyses/blob/master/osf/manage-osf.Rmd)).
- Added package renv for R package management (see [this comment](https://github.com/jvcasillas/many_analyses/issues/3#issuecomment-753976754)).

I will still work on the RR draft so depending on your preferred workflow you can wait for me to be done (I'll let you know). I will make a list tomorrow of things in the RR draft that I need input from you about (which we can maybe discuss in this meeting). I'll also prepare a list of things that remain doing before we can submit the RR.

I will make changes in the OSF repo as per [this comment](https://github.com/jvcasillas/many_analyses/issues/16#issue-777987031). I'll let you know when I am done so you can give feedback if you wish.

**Comment by jvcasillas** [comment]
# 2021/01/06

Meeting notes

- discussed forced alignment of textgrids (long files vs. individual files (per item per subj))
- Figure 2/waveform example for RR intro
- Meta-analysis: include single variable (do you think there is an effect)
- License (will decide later)

**Comment by troettge** [comment]
Figure proposal: 
![Uploading ForkingPaths.png…]()

**Comment by jvcasillas** [comment]
> Figure proposal:
> 
> https://github.com/jvcasillas/many_analyses/blob/master/figs/ForkingPaths.png

That looks awesome! I like it.

**Comment by stefanocoretta** [comment]
# 2021/01/13

## Pre-meeting notes

- Discuss meta-analytical model:
  - ⚠️ Need consensus: no population-level effects.
  - ❓ Question: regarding standardisation of the effects, shouldn't we standardise not only the outcome variable, but also the continuous predictors? And what about factor variables?

**Comment by stefanocoretta** [comment]
Yes: https://github.com/jvcasillas/many_analyses/commit/ed046934e28c08038967c0b6b854c3ad7435c3d6

**Comment by stefanocoretta** [comment]
# 2021/01/13

## Pre-meeting notes

- Discuss meta-analytical model.
  - Need consensus: no population-level predictors in the MA model.
  - Question: regarding standardising predictors, shouldn't we do that not only for the outcome variable but also for the predictors?
- Project management:
  - Keeping minutes:
     - [I had listed several options but now that the comment was deleted I'll only write one] Using a single issue to keep minutes is a bit impractical, you have to scroll down to the bottom and the list is growing. We could maybe use separate issues per meeting and tag them with the `meetings` tag or else.
   - GitHub Notifications:
     - It seems that when comments are edited, people don't get notified. Only when comments or issues are created, or with a direct mention with `@`.
